apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameplay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameplay
  template:
    metadata:
      labels:
        app: gameplay
    spec:
      containers:
          - name: gameplay-nextjs-container
            image: anthlr/scalabilite-gameplay-front:latest
            ports:
                - containerPort: 3000
            volumeMounts:
              - name: app-volume
                mountPath: /app
      volumes:
        - name: app-volume
          hostPath:
            path: /app
